sudo: required
services:
  - docker

before_install:
  - cp .env.example .env

script:
  - docker-compose build
  - docker-compose run php composer install
  - docker-compose run php php vendor/bin/phpunit
