services:
  - docker

cache:
  directories:
    - node_modules
    - vendor  

before_install:
  - nvm install 12

before_script:  
  - cp .env.example .env
  - npm install
  - npm run testing


script:
  - docker-compose run php vendor/bin/phpunit
