services:
  - docker

cache:
  directories:
    - docker_images
    - node_modules
    - vendor  

before_install:
  - nvm install 12
  - docker load -i docker_images/images.tar || true

before_script:  
  - cp .env.example .env
  - npm install
  - npm run testing

script:
  - docker-compose run php vendor/bin/phpunit

before_cache:
  - docker save -o docker_images/images.tar $(docker images -a -q)
